server:
  port: 12001

spring:
  application:
    name: lanting-server
  datasource:
    url: jdbc:mysql://localhost:3306/lanting?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  redis:
    host: ${REDIS_DOMAIN:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: lanting-group

logging:
  level:
    org.apache.kafka.clients: ERROR

lanting:
  secrets:
    wechat-token: ${WECHAT_TOKEN:}
  constants:
    webdriverpath: ${WEB_DRIVER_PATH:/Users/wang.boyang/Downloads/chromedriver}
    singlepagepath: ${SINGLE_PAGE_PATH:/Users/wang.boyang/Projects/mine/lanting/server/clipper/cli}